### ISSUE TITLE
[bug]NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26164(net.minecraft.class_6862)" because "blockstate" is null

### ISSUE THREAD

**Issue by DCTANT** [Snownee/SnowRealMagic#338]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.1.2

### Modloader version

Fabric0.14.24

### Modpack info

https://www.bilibili.com/video/BV1Tu4y157K9/

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/WPWt9nzB

### Issue description

Cannot enter the game, and i don't know how to fix it. Please help me.

Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26164(net.minecraft.class_6862)" because "blockstate" is null
	at snownee.snow.block.ShapeCaches.get(ShapeCaches.java:51) ~[SnowRealMagic-1.20.1-fabric-9.1.2.jar:?]
	at snownee.snow.block.SnowFenceBlock.method_9549(SnowFenceBlock.java:27) ~[SnowRealMagic-1.20.1-fabric-9.1.2.jar:?]
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:1043) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_37403(class_4970.java:355) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:1248) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_2251.method_26246(class_4970.java:489) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26230(class_4970.java:1145) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67) ~[%5B钠%5D%20sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.model.light.data.ArrayLightDataCache.get(ArrayLightDataCache.java:53) ~[%5B钠%5D%20sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.get(LightDataAccess.java:35) ~[%5B钠%5D%20sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at link.infra.indium.renderer.aocalc.AoCalculator.computeFace(AoCalculator.java:440) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.aocalc.AoCalculator.computeFace(AoCalculator.java:327) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.aocalc.AoCalculator.blendedInsetFace(AoCalculator.java:215) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.aocalc.AoCalculator.blendedPartialFace(AoCalculator.java:236) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.aocalc.AoCalculator.calcEnhanced(AoCalculator.java:183) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.aocalc.AoCalculator.compute(AoCalculator.java:132) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext.shadeQuad(AbstractBlockRenderContext.java:146) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.shadeQuad(TerrainRenderContext.java:102) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:128) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:74) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:261) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-38d52f0edc48f475.jar:?]
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-38d52f0edc48f475.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64) ~[【材质连接】continuity-3.0.0-beta.4+1.20.1.jar:?]
	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:601) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-38d52f0edc48f475.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[【材质连接】continuity-3.0.0-beta.4+1.20.1.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-38d52f0edc48f475.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72) ~[【材质连接】continuity-3.0.0-beta.4+1.20.1.jar:?]
	at snownee.snow.client.FabricRendererRenderAPI.translateYAndRender(FabricRendererRenderAPI.java:54) ~[SnowRealMagic-1.20.1-fabric-9.1.2.jar:?]
	at snownee.snow.client.SnowClient.renderHook(SnowClient.java:59) ~[SnowRealMagic-1.20.1-fabric-9.1.2.jar:?]
	at snownee.snow.client.model.SnowCoveredModel.emitBlockQuads(SnowCoveredModel.java:30) ~[SnowRealMagic-1.20.1-fabric-9.1.2.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[%5B铟%5D%20indium-1.0.27+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$fem000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[%5B钠%5D%20sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[%5B钠%5D%20sodium-fabric-mc1.20.1-0.5.3.jar:?]
	... 4 more

**Comment by Snownee** [comment]
1. I don't think it's caused by my mod. maybe sodium, maybe indium, I don't know.
2. The relevant code in my mod will be removed in the next few weeks as I am updating my mod to a new major version. So the issue will probably disappear at that time
