### ISSUE TITLE
Crash while loading in Forge 30.0.18

### ISSUE THREAD

**Issue by jhodgski** [Snownee/SnowRealMagic#38]
* Minecraft Version: 1.51.1
 * Mod Version: cfm-7.0.0-pre15-mc1.15.1 (Mr Crayfish's Furniture mod)

[29Dec2019 19:58:40.073] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, EnderDragonXCX, --version, 1.15.1-forge-30.0.18, --gameDir, C:\Users\Chrissy\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Chrissy\AppData\Roaming\.minecraft\assets, --assetIndex, 1.15, --uuid, 34f5e9fe22004a869d5c3a1758d9a065, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 30.0.18, --fml.mcVersion, 1.15.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20191217.105819]
[29Dec2019 19:58:40.082] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_51 by Oracle Corporation
[29Dec2019 19:58:40.497] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[29Dec2019 19:58:42.394] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.15.1-forge-30.0.18, --gameDir, C:\Users\Chrissy\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Chrissy\AppData\Roaming\.minecraft\assets, --uuid, 34f5e9fe22004a869d5c3a1758d9a065, --username, EnderDragonXCX, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release]
[29Dec2019 19:58:45.334] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: EnderDragonXCX
[29Dec2019 19:58:57.977] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[29Dec2019 19:59:01.163] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 30.0.18, for MC 1.15.1 with MCP 20191217.105819
[29Dec2019 19:59:01.164] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v30.0.18 Initialized
[29Dec2019 19:59:08.212] [modloading-worker-3/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity cfm:seat
[29Dec2019 19:59:11.853] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[29Dec2019 19:59:11.946] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Mod Resources, Programmer Art, Default
[29Dec2019 19:59:24.070] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[29Dec2019 19:59:24.164] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: net.minecraftforge.fml.client.registry.ClientRegistry.bindTileEntityRenderer(Lnet/minecraft/tileentity/TileEntityType;Lnet/minecraft/client/renderer/tileentity/TileEntityRenderer;)V
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2055/1504320796@52027d8b
java.lang.NoSuchMethodError: net.minecraftforge.fml.client.registry.ClientRegistry.bindTileEntityRenderer(Lnet/minecraft/tileentity/TileEntityType;Lnet/minecraft/client/renderer/tileentity/TileEntityRenderer;)V
	at com.mrcrayfish.furniture.proxy.ClientProxy.onSetupClient(ClientProxy.java:56)
	at com.mrcrayfish.furniture.FurnitureMod.onClientSetup(FurnitureMod.java:37)
	at com.mrcrayfish.furniture.FurnitureMod$$Lambda$2257/1396782664.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2055/1504320796.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2168/1002194889.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2154/1191049963.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2154/1191049963.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134)
	at net.minecraftforge.fml.ModList$$Lambda$2225/1521157700.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1867)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2042)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:404)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134)
	at net.minecraftforge.fml.ModList$$Lambda$2207/1627979043.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[29Dec2019 19:59:24.169] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid cfm
java.lang.NoSuchMethodError: net.minecraftforge.fml.client.registry.ClientRegistry.bindTileEntityRenderer(Lnet/minecraft/tileentity/TileEntityType;Lnet/minecraft/client/renderer/tileentity/TileEntityRenderer;)V
	at com.mrcrayfish.furniture.proxy.ClientProxy.onSetupClient(ClientProxy.java:56) ~[?:7.0.0-pre15-1.15.1]
	at com.mrcrayfish.furniture.FurnitureMod.onClientSetup(FurnitureMod.java:37) ~[?:7.0.0-pre15-1.15.1]
	at com.mrcrayfish.furniture.FurnitureMod$$Lambda$2257/1396782664.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2055/1504320796.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:30.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2168/1002194889.accept(Unknown Source) [?:30.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2154/1191049963.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2154/1191049963.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2225/1521157700.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1867) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2042) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:404) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2207/1627979043.run(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[29Dec2019 19:59:24.197] [Server-Worker-3/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SIDED_SETUP, 1 errors found
[29Dec2019 19:59:24.198] [Server-Worker-3/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2046/124246457.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2634/591211382.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2046/124246457.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[29Dec2019 19:59:27.144] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: BETA Current: 30.0.18 Target: 30.0.18
[29Dec2019 19:59:27.145] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Starting version check at https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cfm/update.json
[29Dec2019 19:59:27.352] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Found status: BETA Current: 7.0.0-pre15 Target: null
[29Dec2019 19:59:31.512] [Server-Worker-1/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[29Dec2019 19:59:31.513] [Server-Worker-1/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[29Dec2019 19:59:31.513] [Server-Worker-1/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2046/124246457.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:136) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2636/1682716048.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[29Dec2019 19:59:31.779] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[29Dec2019 19:59:31.781] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[29Dec2019 19:59:32.190] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[29Dec2019 19:59:33.121] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[29Dec2019 19:59:33.126] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[29Dec2019 19:59:33.163] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[29Dec2019 19:59:33.206] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[29Dec2019 19:59:33.218] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[29Dec2019 19:59:33.232] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[29Dec2019 19:59:35.235] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[29Dec2019 19:59:35.278] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[29Dec2019 19:59:35.283] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

**Comment by Snownee** [comment]
I cannot see the relation with my mods
