### ISSUE TITLE
ModernFix Report:  Async chunk load took way too long

### ISSUE THREAD

**Issue by suerion** [Snownee/SnowRealMagic#414]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

11.0.13

### Modloader version

Fabric 0.16.9

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/Jgf9hRA

### Issue description

ModernFix has said, we need to Report this issue on the appropriate Mod to fix some Issue.

If you need more informations, i could check on my dev enviroment here.

```
[00:12:52] [minecraft_overworld - Light/ERROR]: Async chunk load took way too long, this needs to be reported to the appropriate mod.
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at knot/net.minecraft.class_3215.handler$gfn000$modernfix$bailIfServerDead(class_3215.java:11124) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3215.method_12121(class_3215.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_8402(class_1937.java:208) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_22350(class_1937.java:7584) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_8500(class_1937.java:7579) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_8321(class_1937.java:596) ~[server-intermediary.jar:?]
	at knot/snownee.snow.block.SnowVariant.srm$getRaw(SnowVariant.java:29) ~[SnowRealMagic-1.21.1-Fabric-11.0.13.jar:?]
	at knot/snownee.snow.block.ShapeCaches.get(ShapeCaches.java:38) ~[SnowRealMagic-1.21.1-Fabric-11.0.13.jar:?]
	at knot/snownee.snow.block.SRMSnowLayerBlock.method_9530(SRMSnowLayerBlock.java:68) ~[SnowRealMagic-1.21.1-Fabric-11.0.13.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4970.method_9579(MixinBlockBehaviour.java:419) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26167(class_4970.java:925) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4970.method_9505(MixinBlockBehaviour.java:328) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4970$class_4971.method_26193(class_4970.java:932) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3558.method_50017(class_3558.java:105) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3572.method_51531(class_3572.java:172) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3558.method_51567(class_3558.java:199) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3558.method_15516(class_3558.java:175) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3568.method_15516(class_3568.java:56) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3227.method_14277(class_3227.java:185) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3227.method_19505(class_3227.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Snownee** [comment]
What does the chunk look like? Did you place too many snow-covered building blocks? It is not normal for a chunk to take 10 seconds to load.

https://github.com/embeddedt/ModernFix/blob/1.21.1/common/src/main/java/org/embeddedt/modernfix/common/mixin/feature/stalled_chunk_load_detection/ServerChunkCacheMixin.java#L58

**Comment by suerion** [comment]
hey, i had done nothing, only lets the world gen load the world normaly.

its a long time, since the issue i get, don't know anymore, if there was an issue again

will look on this later again. thats only the issue from modernfix,

**Comment by Asosk04** [comment]
Same thing happens here, I'm on Fabric 0.16.14, Minecraft 1.21.1 and Snow Real Magic 12.0.6

I wasn't in a snowy biome

Thread dump from ModernFix:

[\[212936\] \[ModernFix integrated serv.txt](https://github.com/user-attachments/files/20428848/212936.ModernFix.integrated.serv.txt)

Check "minecraft_overworld - Light" thread
