### ISSUE TITLE
Crash with the mod

### ISSUE THREAD

**Issue by emanuele246gi** [Snownee/SnowRealMagic#55]
I have recently ran into a problem with the mod, I don't know why does it do this, it never happened before :(

---- Minecraft Crash Report ----
// You're mean.

Time: 06/03/20 20.20
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at doggytalents.ModBlocks.registerBlockColours(ModBlocks.java:46) ~[?:1.15.2.3] {re:classloading,pl:object_holder_definalize:A}
	at doggytalents.DoggyTalentsMod$$Lambda$3077/1857965187.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2092/557666697.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$4772/882180426.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:198) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:minecraft,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1918121287.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at doggytalents.ModBlocks.registerBlockColours(ModBlocks.java:46)
	at doggytalents.DoggyTalentsMod$$Lambda$3077/1857965187.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2092/557666697.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at net.minecraftforge.fml.ModLoader$$Lambda$4772/882180426.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:198)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1918121287.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2094907352 bytes (1997 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		blood-particles-1.15.2-v1.0.0.jar Blood Particles {blood_particles@1.0.0 CREATE_REGISTRIES}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 CREATE_REGISTRIES}
		nethercraft-1.15.2-1.0.6.jar Nethercraft {nethercraft@1.0.6 CREATE_REGISTRIES}
		AdvancedSkinCustomization-2.8.jar Advanced Skin Customization {advskinmod@2.8 CREATE_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 CREATE_REGISTRIES}
		[Forge]+RFTL+1.5.2+R.jar Advanced Rotten Flesh to Leather {sonyikaarftl@1.5.2 CREATE_REGISTRIES}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 CREATE_REGISTRIES}
		Industrial Agriculture[Core]-1.15.2-1.6.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.6.0 CREATE_REGISTRIES}
		music_player-1.15.2-2.0.13.64.jar Music Player {musicplayer@2.0.13.64 CREATE_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 CREATE_REGISTRIES}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 CREATE_REGISTRIES}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 CREATE_REGISTRIES}
		CoffeeSpawner-1.15.1-6.0.0.jar Coffee Spawner {coffeespawner@1.15.1-6.0.0 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 CREATE_REGISTRIES}
		ResourcefulTools-1.15.2-1.1.20.jar Resourceful Tools {resourceful_tools@1.1.20 CREATE_REGISTRIES}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		Elementary+Staffs+1.6.jar Elementary Staffs {element@1.6 CREATE_REGISTRIES}
		beaconsforall-FORGE-1.15.2-3.0.jar Beacons For All {beaconsforall@FORGE-1.15.2-3.0 CREATE_REGISTRIES}
		modrops-1.0.0_Beta_Two.jar Mo'Drops {modrops@1.0.0_Beta_Two CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.0.1.jar Bookshelf {bookshelf@5.0.1 CREATE_REGISTRIES}
		guardvillagers-1.15.2-1.0.1.jar Guard Villagers {guardvillagers@1.0.1 CREATE_REGISTRIES}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 CREATE_REGISTRIES}
		DarkUtilities-1.15.2-3.0.1.jar Dark Utilities {darkutils@3.0.1 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.0.6.jar Apotheosis {apotheosis@3.0.6 CREATE_REGISTRIES}
		Morpheus-1.15.2-4.2.47.jar Morpheus {morpheus@version CREATE_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.14.406.jar Mekanism: Generators {mekanismgenerators@9.9.14 CREATE_REGISTRIES}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 CREATE_REGISTRIES}
		carpetstairsmod-mc1.15-v1.3.jar Carpet Stairs Mod {carpetstairsmod@1.1 CREATE_REGISTRIES}
		FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 CREATE_REGISTRIES}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 CREATE_REGISTRIES}
		Industrial-Reborn-1.15.2-0.2.2.jar Industrial Reborn {indreb@1.15.2-0.2.2 CREATE_REGISTRIES}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 CREATE_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 CREATE_REGISTRIES}
		improved-stations-1.0.jar Improved Stations {improved-stations@1.0 CREATE_REGISTRIES}
		AmbientSounds_v3.0.17_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.348-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.348 CREATE_REGISTRIES}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 CREATE_REGISTRIES}
		Lollipop-1.15.2-1.0.8.jar Lollipop {lollipop@1.0.8 CREATE_REGISTRIES}
		ironfurnaces-1.15.2-2.0.1.jar Iron Furnaces {ironfurnaces@2.0.1 CREATE_REGISTRIES}
		wtbw_lib-1.15.2-1.0.9.jar WTBW Library {wtbw_lib@1.0.9 CREATE_REGISTRIES}
		SilentGear-1.15.2-1.5.3+78.jar Silent Gear {silentgear@1.5.3+78 CREATE_REGISTRIES}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 CREATE_REGISTRIES}
		ferroustry-2.2.jar Ferroustry {ferroustry@2.2 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.jar Curios API {curios@FORGE-1.15.2-2.0 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 CREATE_REGISTRIES}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 CREATE_REGISTRIES}
		obfuscate-0.3.4-1.15.2.jar Obfuscate {obfuscate@0.3.4 CREATE_REGISTRIES}
		AttainedDrops-1.15.2-6.0.3.jar Attained Drops {attained_drops@6.0.3 CREATE_REGISTRIES}
		NaturesAura-23.2.jar Nature's Aura {naturesaura@version CREATE_REGISTRIES}
		MekanismTools-1.15.2-9.9.14.406.jar Mekanism: Tools {mekanismtools@9.9.14 CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 CREATE_REGISTRIES}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 CREATE_REGISTRIES}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 CREATE_REGISTRIES}
		betterwithminecolonies-1.15.2-1.15.16.jar Better With Minecolonies {betterwithminecolonies@1.15.2-1.15.16 CREATE_REGISTRIES}
		AdChimneys-1.15.2-5.0.2.0-build.0007.jar Advanced Chimneys {adchimneys@5.0.2.0 CREATE_REGISTRIES}
		tramplestopper-1.15.2-2.0.0.beta-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.beta-universal CREATE_REGISTRIES}
		controllable-1.15.2-0.8.0.jar Controllable {controllable@0.8.0 CREATE_REGISTRIES}
		TofuCraftReload-1.15.2-0.0.0.4.2.jar TofuCraftReload {tofucraft@0.0.0.4.2 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.1.11.jar Cyclic {cyclic@1.15.2-0.1.11 CREATE_REGISTRIES}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 CREATE_REGISTRIES}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 CREATE_REGISTRIES}
		ClientTweaks_1.15.2-4.1.0.jar Client Tweaks {clienttweaks@4.1.0 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 CREATE_REGISTRIES}
		Inventory-Spam-Mod-1.15.2.jar Inventory Spam {inventoryspam@version CREATE_REGISTRIES}
		flamboyant-2.0.0.jar Flamboyant {flamboyant@2.0.0 CREATE_REGISTRIES}
		Equipment-Tooltips-Mod-1.15.2.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 CREATE_REGISTRIES}
		janoeo-3.1.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.1.2 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		JustEnoughCalculation-1.15.2-3.5.0.jar Just Enough Calculation {jecalculation@3.5.0 CREATE_REGISTRIES}
		buzzierbees-1.1.4.jar Buzzier Bees {buzzierbees@1.1.4 CREATE_REGISTRIES}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 CREATE_REGISTRIES}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 CREATE_REGISTRIES}
		Mekanism-1.15.2-9.9.14.406.jar Mekanism {mekanism@9.9.14 CREATE_REGISTRIES}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 CREATE_REGISTRIES}
		enviromats-1.15.2-2.0.2.1.jar Environmental Materials {enviromats@1.15.2-2.0.2.1 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		good-nights-sleep-1.15.2-1.0.2.jar Good Night's Sleep {goodnightsleep@1.0.2 CREATE_REGISTRIES}
		EnderBags-Mod-1.15.2.jar Ender Bags {ender_bags@5.0.0 CREATE_REGISTRIES}
		gardentools-1.15.2-1.0.0.jar Garden Tools {gardentools@1.15.2-1.0.0 CREATE_REGISTRIES}
		DimStorage-1.15.2-3.0.1.jar DimStorage {dimstorage@3.0.1 CREATE_REGISTRIES}
		decorative_blocks_6b.jar Decorative Blocks {decorative_blocks@1.6 CREATE_REGISTRIES}
		engineerstools-1.15.2-1.0.6-b2.jar Engineer's Tools {engineerstools@1.0.6-b2 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 CREATE_REGISTRIES}
		FarmingForBlockheads_1.15.2-6.1.0.jar Farming for Blockheads {farmingforblockheads@6.1.0 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		alib-1.15.2-1.jar A Lib {alib@1.15.2-1 CREATE_REGISTRIES}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha CREATE_REGISTRIES}
		bedspreads-FORGE-1.15.2-3.0.jar Bedspreads {bedspreads@FORGE-1.15.2-3.0 CREATE_REGISTRIES}
		CraftTweaker-1.15.2-6.0.0.9.jar CraftTweaker {crafttweaker@6.0.0.9 CREATE_REGISTRIES}
		allmobsattackvillagers-1.0-1.15.2.jar All Mobs Attack Villagers {allmobsattackvillagers@1.0 CREATE_REGISTRIES}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 CREATE_REGISTRIES}
		GoProne-Mod-1.15.2.jar GoProne {goprone@1.15.x-1.1.1 CREATE_REGISTRIES}
		wtbw_core-1.15.2-1.0.10.jar WTBW Core {wtbw_core@1.0.10 CREATE_REGISTRIES}
		wtbw_tools-1.15.2-1.0.10.jar WTBW Tools {wtbw_tools@1.0.10 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 ERROR}
		ironchest-1.15.2-10.0.2.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		alchemistry-1.15.2-5.jar Alchemistry {alchemistry@1.15.2-5 CREATE_REGISTRIES}
		forge-1.15.2-31.1.18-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b CREATE_REGISTRIES}
		Lucky-Block-Mod-1.15.2.jar Lucky Block {lucky@1.15.2-1 CREATE_REGISTRIES}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 CREATE_REGISTRIES}
		mcpaint-1.5.0.jar Mc Paint {mcpaint@1.5.0 CREATE_REGISTRIES}
		instahouses-1.15.2-1.1.1.jar Slashkings InstaHouses {instahouses@1.1 CREATE_REGISTRIES}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 CREATE_REGISTRIES}
		bluepower-1.15.2-0.4.184-alpha-universal.jar Blue Power {bluepower@0.4.184-alpha CREATE_REGISTRIES}
		wtbw_machines-1.15.2-1.0.9.jar WTBW Machines {wtbw_machines@1.0.9 CREATE_REGISTRIES}
		concreteconversion-1.15.2-4.0.0.0.jar Concrete Conversion {concreteconversion@1.15.2-4.0.0.0 CREATE_REGISTRIES}
		C.O.M.B.A.T-1.15.2-4.0.6.jar C.O.M.B.A.T {combat@4.0.6 CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.2-beta-2.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 CREATE_REGISTRIES}
		AdLods-1.15.2-3.0.0.0-build.0004.jar Large Ore Deposits {adlods@3.0.0.0 CREATE_REGISTRIES}
		customquests-1.15.2-1.0.0.jar Custom Quests {customquests@1.15.2-1.0.0 CREATE_REGISTRIES}
		car-1.15.2-2.0.4.jar Ultimate Car Mod {car@1.15.2-2.0.4 CREATE_REGISTRIES}
		dimdungeons-1.04-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.04 CREATE_REGISTRIES}
		Industrial Agriculture[Omega Craft]-1.15.2-1.6.0.jar Industrial Agriculture Plugin-Omega Craft {iapoc@1.15.2-1.6.0 CREATE_REGISTRIES}
		flux-4.8.6.jar Flux {flux@4.8.6 CREATE_REGISTRIES}
		fl-3.0.11.jar Flux Library {fl@3.0.11 CREATE_REGISTRIES}
		chemlib-1.15.2-2.jar Chem Lib {chemlib@1.15.2-2 CREATE_REGISTRIES}
		lava-monster-1.15.2-1.0.2.jar Lava Monster {lava_monster@1.0.2 CREATE_REGISTRIES}
		corail_recycler-4.0.2-1.15.2.jar Corail Recycler {corail_recycler@4.0.2 CREATE_REGISTRIES}
		[1.15.2]+SecurityCraft+v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 CREATE_REGISTRIES}
		DoubleSlabs-1.15-2.0.1.jar Double Slabs {doubleslabs@2.0.1 CREATE_REGISTRIES}
		structurize-0.10.272-ALPHA.jar Structurize {structurize@0.10.272-ALPHA CREATE_REGISTRIES}
		AmbientEnvironment-3.0.0.jar Ambient Environment {ambientenvironment@3.0.0 CREATE_REGISTRIES}
		minecolonies-0.10.738-ALPHA-universal.jar Minecolonies {minecolonies@0.10.738-ALPHA CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		engineersdecor-1.15.2-1.0.19-b5.jar Engineer's Decor {engineersdecor@1.0.19-b5 CREATE_REGISTRIES}
		DoubleConnectedGlass_1.15.2_v01.jar DoubleConnectedGlass {connectedglass@v01 CREATE_REGISTRIES}
		ilikewood-1.15.2-2.1.0.0.jar I Like Wood {ilikewood@1.15.2-2.1.0.0 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.9.jar Aquaculture 2 {aquaculture@1.15.2-2.0.9 CREATE_REGISTRIES}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 CREATE_REGISTRIES}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.0.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.0 CREATE_REGISTRIES}
		MineMenu-1.15.2-1.8.4.jar MineMenu {minemenu@1.15.2-1.8.4 CREATE_REGISTRIES}
		luckyores-1.15.2-1.3.1.jar Lucky Ores Mod {luckyores@1.3 CREATE_REGISTRIES}
		Omega+Craft+4.0.9+-+1.15.2.jar Omega Craft {omegacraft@1.0 CREATE_REGISTRIES}
		lootbagmod-1.15.1-1.5.jar Loot Bag Mod {lootbagmod@1.15.1-1.5 CREATE_REGISTRIES}
		farlanders-1.15.2-1.1.2.jar The Farlanders {farlanders@1.1.2 CREATE_REGISTRIES}
	Launched Version: 1.15.2-forge-31.1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 530 GL version 4.6.0 - Build 26.20.100.7263, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by Snownee** [comment]
https://github.com/percivalalb/DoggyTalents/issues/194
https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by Snownee** [comment]
Not my issue

**Comment by emanuele246gi** [comment]
Yeah I found that it's from Dark Utilities
