### ISSUE TITLE
[1.16.3] Crash on Load with SnowRealMagic Added

### ISSUE THREAD

**Issue by lulabyte** [Snownee/SnowRealMagic#91]
Hello! Thank you for the mod, it's really lovely. We used it in 1.16.1 and now we've upgraded to 1.16.3.

With this mod added, even with the latest Kiwi added as well, I get a crash on game load. When I remove SnowRealMagic I do not get this crash.

Crash Report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/23/20 10:10 AM
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.optifine.shaders.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:60) ~[?:?] {re:classloading}
	at net.optifine.shaders.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:30) ~[?:?] {re:classloading}
	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:901) ~[?:?] {re:classloading}
	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:865) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1154) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:967) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.loadConfig(Shaders.java:739) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.startup(Shaders.java:2077) ~[?:?] {re:classloading}
	at net.optifine.Config.initDisplay(Config.java:220) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.platform.GlStateManager.func_227666_a_(GlStateManager.java:403) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.platform.GLX._init(GLX.java:151) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(SourceFile:1043) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/948692477.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}
Caused by: java.lang.IllegalStateException: Missing: ResourceKey[minecraft:worldgen/biome / minecraft:plains]
	at net.minecraft.util.registry.Registry.func_243576_d(Registry.java:434) ~[?:?] {re:mixin,re:classloading}
	at net.optifine.util.BiomeUtils.<clinit>(BiomeUtils.java:32) ~[?:?] {re:classloading}
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.shaders.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:60) ~[?:?] {re:classloading}
	at net.optifine.shaders.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:30) ~[?:?] {re:classloading}
	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:901) ~[?:?] {re:classloading}
	at net.optifine.shaders.config.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:865) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1154) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:967) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.loadConfig(Shaders.java:739) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.startup(Shaders.java:2077) ~[?:?] {re:classloading}
	at net.optifine.Config.initDisplay(Config.java:220) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.platform.GlStateManager.func_227666_a_(GlStateManager.java:403) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.platform.GLX._init(GLX.java:151) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(SourceFile:1043) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.25.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/948692477.call(Unknown Source) [forge-1.16.3-34.1.25.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3969914304 bytes (3786 MB) / 5100273664 bytes (4864 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.3-forge-34.1.25
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre1.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/97068888-244f8600-15fe-11eb-848c-e294880a48bc.png)
